

class RandomGeneratorPlaylist {

  constructor(_unqfy,_genresToInclude,_maxduration){
    this.unqfy = _unqfy;
    this.genresToInclude = _genresToInclude;
    this.maxDuration = _maxduration;
  }

  autoGenerate(){

    let autoGenerated = [];
    let trackMachedGenres = this.unqfy.getTracksMatchingGenres(this.genresToInclude);
    let actualDuration = 0;
    let nextTrack = null;

    while((!nextTrack || actualDuration + nextTrack.duration <= this.maxDuration) && trackMachedGenres.length > 0){
      if (!nextTrack){
        nextTrack = trackMachedGenres.pop(trackMachedGenres[Math.floor(Math.random()*trackMachedGenres.length)]);
      }
      autoGenerated.push(nextTrack);
      actualDuration += nextTrack.duration;
      nextTrack = trackMachedGenres.pop(trackMachedGenres[Math.floor(Math.random()*trackMachedGenres.length)]);
    }
    return autoGenerated;
    
  }

}


module.exports = {
  RandomGeneratorPlaylist,
};